import * as React from "react"
import { Link } from "gatsby"
import { StaticImage } from "gatsby-plugin-image"

import { useStaticQuery, graphql } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

const IndexPage = () => {
  const data = useStaticQuery(graphql`
    {
      allSanitySiteSettings {
        edges {
          node {
            headerblock {
              hdrlogo {
                asset {
                 url
                }
              }
            }
            sitetitle
          }
        }
      }
    }
  `)

  return (
    <>
      <Layout>
        <SEO title="Home" />
        {/* Hero */}
        <div className="pt-24">

          <div className="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">

            <div className="flex flex-col w-full md:w-2/5 justify-center items-start text-center md:text-left">
              <p className="uppercase tracking-loose w-full">Open-Source project</p>
              <h1 className="my-4 text-5xl font-bold leading-tight">GatsbyJS Tailwind Starter</h1>
              <p className="leading-normal text-2xl mb-8">
                - a simple landing page styled with <a className="text-gray-800 font-bold underline" href="https://tailwindcss.com/">Tailwind CSS</a> 
                {' '} and generated by <a className="text-gray-800 font-bold underline" href="https://www.gatsbyjs.org/">GatsbyJS</a>
              </p>

              <form>
                <button type="submit" className="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg">Get Sources</button>
              </form>

            </div>

            <div className="w-full md:w-3/5 py-6 text-center">
              <img className="w-full md:w-4/5 z-50" src={data.allSanitySiteSettings.edges[0].node.headerblock.hdrlogo.asset.url} alt={data.allSanitySiteSettings.edges[0].node.sitetitle} />
            </div>
            
          </div>

        </div>
        <h1>Hi people</h1>
        <p>Welcome to your new Gatsby site.</p>
        <p>Now go build something great.</p>
        <StaticImage
          src="../images/gatsby-astronaut.png"
          width={300}
          quality={95}
          formats={["AUTO", "WEBP", "AVIF"]}
          alt="A Gatsby astronaut"
          style={{ marginBottom: `1.45rem` }}
        />
        <p>
          <Link to="/page-2/">Go to page 2</Link> <br />
          <Link to="/using-typescript/">Go to "Using TypeScript"</Link>
        </p>
      </Layout>
    </>
  )
}

export default IndexPage
